/**
 * Centralized Background Color System
 *
 * Provides consistent background colors across all themes with optimal
 * readability based on accessibility research (WCAG AAA ~8:1 contrast).
 *
 * Usage:
 *   const bg = createBackgroundColors(270, 0.12); // Purple hue, 12% saturation
 *   // Use bg.background, bg.surface, etc. in palette
 */

import { colord } from 'colord'

/**
 * Master lightness constant for all theme backgrounds.
 * Change this single value to adjust all themes at once.
 *
 * Recommended values:
 * - 0.07: High contrast (GitHub-like)
 * - 0.10: Optimal for long coding sessions (default)
 * - 0.12: Softer contrast
 */
export const BACKGROUND_LIGHTNESS = 0.10

/**
 * Background-related colors generated by createBackgroundColors()
 */
export interface BackgroundColors {
  background: string
  surface: string
  surfaceDark: string
  surfaceLight: string
  border: string
  overlay: string
  panelBackground: string
}

/**
 * Convert HSL values to hex color string.
 *
 * @param h - Hue (0-360)
 * @param s - Saturation (0-1)
 * @param l - Lightness (0-1)
 * @returns Hex color string
 */
export function hslToHex(h: number, s: number, l: number): string {
  return colord({ h, s: s * 100, l: l * 100 }).toHex()
}

/**
 * Generate all background-related colors from a hue and saturation.
 * Lightness is derived from the BACKGROUND_LIGHTNESS constant.
 *
 * @param hue - Theme's characteristic hue (0-360)
 * @param saturation - Color saturation (0-1), typically 0.08-0.15 for backgrounds
 * @returns Object with all background-related colors
 */
export function createBackgroundColors(
  hue: number,
  saturation: number
): BackgroundColors {
  const l = BACKGROUND_LIGHTNESS

  return {
    background: hslToHex(hue, saturation, l),
    surface: hslToHex(hue, saturation, l),
    surfaceDark: hslToHex(hue, saturation, l * 0.6),
    surfaceLight: hslToHex(hue, saturation, l * 1.5),
    border: hslToHex(hue, saturation, l * 1.8),
    overlay: hslToHex(hue, saturation, l * 1.3),
    panelBackground: hslToHex(hue, saturation, l),
  }
}
